# 기초통계 통합 프로젝트
## Part 2. 표본을 활용한 전체 고객 특성 추정

### 시나리오

Part 1에서는 전체 고객 데이터의 기술통계량과 구매금액 이상치를 확인했습니다.

온라인 쇼핑몰 데이터 분석팀은 전체 고객 데이터를 매번 모두 분석하기 전에,
전체 고객의 수가 많아 일부 고객만 추출해도 전체 고객의 평균 구매 특성을 비슷하게 파악할 수 있는지 확인하려고 합니다.

Part 2에서는 전체 고객 데이터를 모집단으로 설정하고,
서로 다른 크기의 고객 표본을 추출하여 표본평균과 모집단 평균을 비교합니다.

### 과제 목표

#### 학습 목표 
- 모집단과 표본의 의미를 구분할 수 있습니다.
- 전체 고객 데이터에서 무작위표본을 추출할 수 있습니다.
- 모집단 평균과 표본평균을 계산할 수 있습니다.
- 표본 크기에 따른 모집단 평균과의 차이를 비교하고 해석할 수 있습니다.

#### 심화 학습 목표(선택)
- 표본의 대표성 한계를 설명할 수 있습니다.
- 특정 고객 유형의 과다·과소 포함이 결과에 미치는 영향을 설명할 수 있습니다.
- 표본 결과를 전체 고객에게 적용하기 전에 확인할 사항을 제안할 수 있습니다.

### 사용 환경

- 결과물: `.ipynb` 파일 1개
- 사용 언어: Python 3.X
- 사용 라이브러리: pandas, matplotlib
- 사용 데이터: `online_shopping_customer_data.csv`

## 제공 코드. 모집단 데이터 준비

아래 코드는 준비 코드이며 평가 대상이 아닙니다.

Part 1과 동일한 고객 데이터를 사용하고,
`PurchaseAmount`, `MonthlyVisitCount`에 결측치가 없는 고객을 모집단으로 설정합니다.

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

DATA_FILE = "online_shopping_customer_data.csv"

df = pd.read_csv(DATA_FILE)

population_columns = ["PurchaseAmount", "MonthlyVisitCount"]

population_df = df.dropna(subset=population_columns).copy()

print("전체 고객 수:", len(df))
print("분석에 사용할 모집단 고객 수:", len(population_df))

population_df[population_columns].head()

전체 고객 수: 500
분석에 사용할 모집단 고객 수: 487

   PurchaseAmount  MonthlyVisitCount
0         86900.0                6.0
1        287500.0               10.0
2        242100.0               11.0
3        300500.0               15.0
4        171400.0                8.0

# 필수 문제 1. 모집단의 평균 구매 특성 확인

## 업무 상황

분석팀은 표본을 추출하기 전에 전체 고객의 평균 구매금액과 평균 방문횟수를 기준값으로 확인하려고 합니다.

## 요구사항

1. 모집단의 전체 고객 수를 출력합니다.
2. `PurchaseAmount`의 모집단 평균을 계산합니다.
3. `MonthlyVisitCount`의 모집단 평균을 계산합니다.
4. 계산 결과를 하나의 표로 정리합니다.
5. 모집단과 표본의 차이를 한 문장으로 작성합니다.

In [3]:
# 필수 문제 1 코드를 작성하세요.
print('전체 고객 수:', len(population_df))

result = pd.DataFrame({
    "구매 금액":[
       round(population_df['PurchaseAmount'].mean(), 2)
    ],
    "방문 횟수":[
        round(population_df['MonthlyVisitCount'].mean(), 2)
    ]
}, index = ['평균'])

display(result)

print('모집단은 전체 데이터를, 표본은 그 모집단에서 실제로 조사한 일부 데이터라는 차이가 있다.')

전체 고객 수: 487

        구매 금액  방문 횟수
평균  229692.61  10.69

모집단은 전체 데이터를, 표본은 그 모집단에서 실제로 조사한 일부 데이터라는 차이가 있다.

# 필수 문제 2. 서로 다른 크기의 고객 표본 추출 및 비교

## 업무 상황

분석팀은 적은 수의 고객만 확인했을 때와 더 많은 고객을 확인했을 때
전체 고객의 평균 구매 특성을 얼마나 비슷하게 추정할 수 있는지 비교하려고 합니다.

## 요구사항

1. 모집단에서 고객 30명을 무작위로 추출합니다.
2. 모집단에서 고객 100명을 무작위로 추출합니다.
3. 두 표본은 코드를 다시 실행해도 같은 고객이 추출되도록 `random_state`를 설정합니다.
4. 각 표본의 평균 구매금액과 평균 방문횟수를 계산합니다.
5. 모집단 평균과 두 표본평균을 하나의 표로 정리합니다.
6. 모집단 평균과 각 표본평균의 차이를 계산합니다.

## 힌트

- `DataFrame.sample()`을 사용하여 표본을 추출할 수 있습니다.
- 평균 차이는 `표본평균 - 모집단 평균`으로 계산할 수 있습니다.
- 표본은 동일 고객이 중복되지 않도록 추출합니다.

In [4]:
# 필수 문제 2 코드를 작성하세요.
sample_30 = population_df.sample(n=30, random_state=42)
sample_100 = population_df.drop(sample_30.index).sample(n=100, random_state=42)

result_sample = pd.DataFrame({
    "구매 금액":[
        round(population_df['PurchaseAmount'].mean(), 2),
        round(sample_30['PurchaseAmount'].mean(), 2),
        round(sample_100['PurchaseAmount'].mean(), 2),
        round(population_df['PurchaseAmount'].mean()-
              sample_30['PurchaseAmount'].mean(), 2),
        round(population_df['PurchaseAmount'].mean()-
              sample_100['PurchaseAmount'].mean(), 2)
    ],
    "방문 횟수":[
        round(population_df['MonthlyVisitCount'].mean(), 2),
        round(sample_30['MonthlyVisitCount'].mean(), 2),
        round(sample_100['MonthlyVisitCount'].mean(), 2),
        round(population_df['MonthlyVisitCount'].mean()-
              sample_30['MonthlyVisitCount'].mean(), 2),
        round(population_df['MonthlyVisitCount'].mean()-
              sample_100['MonthlyVisitCount'].mean(), 2)     
    ]
}, index = ['모집단 평균', '표본(30명) 평균', '표본(100명) 평균', '평균 차이(30명)', '평균 차이(100명)'])

display(result_sample)

                 구매 금액  방문 횟수
모집단 평균       229692.61  10.69
표본(30명) 평균   219640.00  10.47
표본(100명) 평균  210175.00  10.12
평균 차이(30명)    10052.61   0.22
평균 차이(100명)   19517.61   0.57

# 필수 문제 3. 표본 크기에 따른 모집단 평균 차이 해석

## 업무 상황

분석팀은 30명 표본과 100명 표본의 결과를 비교하여,
표본 크기에 따라 모집단 평균과의 차이가 어떻게 나타났는지 보고하려고 합니다.

## 요구사항

다음 내용을 포함하여 작성합니다.

1. 30명 표본과 100명 표본 중 모집단 평균에 더 가까운 결과를 확인합니다.
2. 표본 크기가 커질 때 모집단 평균과의 차이에 대해 일반적으로 기대할 수 있는 변화를 설명합니다.

> 실제 실행 결과에서 100명 표본이 모든 변수에서 반드시 더 가까워야 하는 것은 아닙니다.  
> 계산된 결과를 그대로 확인한 뒤, 일반적인 경향과 이번 표본의 결과를 구분하여 작성합니다.

In [5]:
# 필수 문제 3 해석에 필요한 값을 출력하고, 아래 마크다운 셀에 해석을 작성하세요.
result_sample = pd.DataFrame({
    "구매 금액":[
        round(population_df['PurchaseAmount'].mean(), 2),
        round(sample_30['PurchaseAmount'].mean(), 2),
        round(sample_100['PurchaseAmount'].mean(), 2),
        round(population_df['PurchaseAmount'].mean()-
              sample_30['PurchaseAmount'].mean(), 2),
        round(population_df['PurchaseAmount'].mean()-
              sample_100['PurchaseAmount'].mean(), 2)
    ],
    "방문 횟수":[
        round(population_df['MonthlyVisitCount'].mean(), 2),
        round(sample_30['MonthlyVisitCount'].mean(), 2),
        round(sample_100['MonthlyVisitCount'].mean(), 2),
        round(population_df['MonthlyVisitCount'].mean()-
              sample_30['MonthlyVisitCount'].mean(), 2),
        round(population_df['MonthlyVisitCount'].mean()-
              sample_100['MonthlyVisitCount'].mean(), 2) 
    ]
}, index = ['모집단 평균', '표본(30명) 평균', '표본(100명) 평균', '평균 차이(30명)', '평균 차이(100명)'])

display(result_sample)

                 구매 금액  방문 횟수
모집단 평균       229692.61  10.69
표본(30명) 평균   219640.00  10.47
표본(100명) 평균  210175.00  10.12
평균 차이(30명)    10052.61   0.22
평균 차이(100명)   19517.61   0.57

### 필수 문제 3 해석 작성

위 사례에서는 30명 표본 평균이 100명 표본 평균보다 모집단 평균에 더 가까운 값을 가지는 것으로 확인되었다.

일반적으로 표본의 크기가 커질수록 표본이 모집단의 특성을 더 안정적으로 반영할 가능성이 높아져 모집단 특성에 가까워지는 경향이 강해진다.

# 심화 문제. 표본의 대표성 한계와 적용 전 확인 사항

## 업무 상황

표본평균이 모집단 평균과 비슷하더라도,
해당 표본이 전체 고객의 다양한 특성을 충분히 포함했다고 단정할 수는 없습니다.

## 요구사항

다음 내용을 포함하여 **3문장 이상** 작성합니다.

1. 무작위표본도 전체 고객을 완벽하게 대표하지 못할 수 있는 이유를 설명합니다.
2. 고액 구매 고객, 방문횟수가 많은 고객 등 특정 고객 유형이 표본에 과다 또는 과소 포함될 때 평균에 미치는 영향을 설명합니다.
3. 표본 결과를 전체 고객에게 적용하기 전에 확인해야 할 사항을 1가지 이상 제안합니다.

### 심화 문제 해석 작성

- 여기에 표본의 대표성 한계와 전체 고객 적용 전 확인 사항을 작성하세요.

# 제출 결과물

## 필수 제출 결과물

| 결과물 | 제출 내용 |
|---|---|
| 모집단 기준값 | 전체 고객 수, 평균 구매금액, 평균 방문횟수 |
| 표본 추출 결과 | 30명 표본과 100명 표본 |
| 평균 비교표 | 모집단 평균과 두 표본의 평균 |
| 평균 차이 | 각 표본평균과 모집단 평균의 차이 |
| 필수 해석 | 표본 크기에 따른 모집단 평균 차이 해석 |

## 심화 제출 결과물(선택)

| 결과물 | 제출 내용 |
|---|---|
| 대표성 한계 해석 | 무작위표본이 전체 고객을 완벽히 대표하지 못할 수 있는 이유 |
| 고객 유형 편중 해석 | 특정 고객 유형의 과다·과소 포함이 평균에 미치는 영향 |
| 적용 전 확인 사항 | 전체 고객 적용 전 확인할 표본 구성 또는 추가 검토 사항 |

# 제출 전 체크리스트

## 필수 체크리스트
- [ ] 모집단과 표본의 의미를 구분했습니다.
- [ ] 모집단 평균을 계산했습니다.
- [ ] 30명과 100명 표본을 중복 없이 무작위로 추출했습니다.
- [ ] `random_state`를 설정했습니다.
- [ ] 각 표본의 평균을 계산했습니다.
- [ ] 모집단 평균과 표본평균을 표로 비교했습니다.
- [ ] 표본별 모집단 평균과의 차이를 계산했습니다.
- [ ] 표본 크기에 따른 평균 차이를 해석했습니다.

## 심화 체크리스트
- [ ] 표본의 대표성 한계를 설명했습니다.
- [ ] 특정 고객 유형의 과다·과소 포함 문제를 설명했습니다.
- [ ] 전체 고객에게 적용하기 전 확인 사항을 제안했습니다.